import { useCallback, useState } from "react"
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  RefreshControl,
  ActivityIndicator,
  Alert,
  Share,
} from "react-native"
import { useFocusEffect } from "expo-router"
import { Ionicons } from "@expo/vector-icons"
import { format, subDays } from "date-fns"
import { DEFAULT_CHECKLIST_ITEMS } from "@agriguard/compliance-data"
import { loadFarm, loadBaseUrl } from "@/lib/storage"
import { setBaseUrl } from "@/lib/api"

interface Farm { id: string; name: string; stateAbbreviation: string; farmType: string }
interface PastReport {
  id: string
  title: string
  periodStart: string
  periodEnd: string
  complianceScore: number | null
  createdAt: string
}

export default function ReportsTab() {
  const [farm, setFarm] = useState<Farm | null>(null)
  const [pastReports, setPastReports] = useState<PastReport[]>([])
  const [periodStart, setPeriodStart] = useState(format(subDays(new Date(), 29), "yyyy-MM-dd"))
  const [periodEnd] = useState(format(new Date(), "yyyy-MM-dd"))
  const [generating, setGenerating] = useState(false)
  const [refreshing, setRefreshing] = useState(false)
  const [avgScore, setAvgScore] = useState<number | null>(null)

  async function load() {
    const f = await loadFarm<Farm>()
    setFarm(f)
    const url = await loadBaseUrl()
    if (url && f) {
      setBaseUrl(url)
      try {
        const res = await fetch(`${url}/api/reports?farmId=${f.id}`)
        if (res.ok) {
          const data = await res.json()
          setPastReports(data.reports ?? [])
        }
      } catch {
        // Offline — show cached data
      }
    }
  }

  useFocusEffect(useCallback(() => { load() }, []))

  async function onRefresh() {
    setRefreshing(true)
    await load()
    setRefreshing(false)
  }

  async function generateReport() {
    if (!farm) { Alert.alert("Error", "No farm data found. Please sync with the web app."); return }
    setGenerating(true)
    try {
      const url = await loadBaseUrl()
      if (!url) { Alert.alert("Not connected", "Please configure the server URL in Settings."); return }

      const res = await fetch(`${url}/api/reports`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ farmId: farm.id, periodStart, periodEnd }),
      })
      if (res.ok) {
        const data = await res.json()
        setAvgScore(data.complianceScore)
        Alert.alert(
          "Report Generated",
          `Compliance Score: ${data.complianceScore}%\n\nYour report has been saved and is available on the web app.`,
          [{ text: "OK" }],
        )
        await load()
      } else {
        Alert.alert("Error", "Failed to generate report. Please try again.")
      }
    } catch {
      Alert.alert("Connection error", "Could not reach the server.")
    } finally {
      setGenerating(false)
    }
  }

  async function shareReport(report: PastReport) {
    try {
      await Share.share({
        title: report.title,
        message: `AgriGuard Compliance Report\n${report.title}\nPeriod: ${report.periodStart} to ${report.periodEnd}\nCompliance Score: ${report.complianceScore ?? "N/A"}%\n\nGenerated by AgriGuard Farm Compliance Platform`,
      })
    } catch {
      // User cancelled
    }
  }

  // Calculate local score estimate from stored completions
  const farmType = farm?.farmType ?? "mixed"
  const requiredItems = DEFAULT_CHECKLIST_ITEMS.filter(
    (i) =>
      i.frequency === "daily" &&
      i.required &&
      (i.applicableTo.includes("all") || i.applicableTo.includes(farmType as never)),
  )

  const scoreColor = (score: number) =>
    score >= 90 ? "#16a34a" : score >= 70 ? "#d97706" : "#dc2626"

  return (
    <ScrollView
      style={styles.screen}
      contentContainerStyle={styles.content}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#166534" />}
    >
      <Text style={styles.title}>Compliance Reports</Text>
      <Text style={styles.subtitle}>Generate audit-ready reports for USDA inspections and lender audits</Text>

      {/* Generate Report Card */}
      <View style={styles.card}>
        <Text style={styles.cardTitle}>Generate New Report</Text>

        <View style={styles.periodRow}>
          <View style={styles.periodField}>
            <Text style={styles.label}>Period Start</Text>
            <Text style={styles.periodValue}>{format(new Date(periodStart + "T12:00:00"), "MMM d, yyyy")}</Text>
          </View>
          <Ionicons name="arrow-forward" size={16} color="#9ca3af" />
          <View style={styles.periodField}>
            <Text style={styles.label}>Period End</Text>
            <Text style={styles.periodValue}>{format(new Date(periodEnd + "T12:00:00"), "MMM d, yyyy")}</Text>
          </View>
        </View>

        <View style={styles.previewRow}>
          <View style={styles.previewStat}>
            <Text style={styles.previewStatValue}>{requiredItems.length}</Text>
            <Text style={styles.previewStatLabel}>Required Tasks</Text>
          </View>
          <View style={styles.previewStat}>
            <Text style={styles.previewStatValue}>30</Text>
            <Text style={styles.previewStatLabel}>Days Tracked</Text>
          </View>
          {avgScore !== null && (
            <View style={styles.previewStat}>
              <Text style={[styles.previewStatValue, { color: scoreColor(avgScore) }]}>{avgScore}%</Text>
              <Text style={styles.previewStatLabel}>Compliance</Text>
            </View>
          )}
        </View>

        <TouchableOpacity
          style={[styles.btn, generating && styles.btnDisabled]}
          onPress={generateReport}
          disabled={generating}
        >
          {generating ? (
            <ActivityIndicator color="#fff" size="small" />
          ) : (
            <>
              <Ionicons name="document-text-outline" size={18} color="#fff" />
              <Text style={styles.btnText}>Generate Report</Text>
            </>
          )}
        </TouchableOpacity>

        <Text style={styles.hint}>
          Reports are saved to your account and accessible on the web app for printing.
        </Text>
      </View>

      {/* Compliance Disclaimer */}
      <View style={styles.disclaimerCard}>
        <Ionicons name="information-circle-outline" size={18} color="#166534" />
        <Text style={styles.disclaimerText}>
          Records must be retained for a minimum of 2 years per FSMA and EPA FIFRA requirements.
        </Text>
      </View>

      {/* Past Reports */}
      {pastReports.length > 0 && (
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Previous Reports ({pastReports.length})</Text>
          {pastReports.map((report, i) => (
            <View key={report.id} style={[styles.reportRow, i < pastReports.length - 1 && styles.reportRowBorder]}>
              <View style={styles.reportInfo}>
                <Text style={styles.reportTitle} numberOfLines={1}>{report.title}</Text>
                <Text style={styles.reportPeriod}>
                  {report.periodStart} → {report.periodEnd}
                </Text>
                <Text style={styles.reportDate}>
                  {format(new Date(report.createdAt), "MMM d, yyyy")}
                </Text>
              </View>
              <View style={styles.reportRight}>
                {report.complianceScore !== null && (
                  <Text style={[styles.reportScore, { color: scoreColor(report.complianceScore) }]}>
                    {report.complianceScore}%
                  </Text>
                )}
                <TouchableOpacity onPress={() => shareReport(report)} style={styles.shareBtn}>
                  <Ionicons name="share-outline" size={18} color="#166534" />
                </TouchableOpacity>
              </View>
            </View>
          ))}
        </View>
      )}

      {pastReports.length === 0 && !generating && (
        <View style={styles.empty}>
          <Ionicons name="document-text-outline" size={48} color="#d1d5db" />
          <Text style={styles.emptyText}>No reports yet</Text>
          <Text style={styles.emptySubtext}>Generate your first compliance report above</Text>
        </View>
      )}
    </ScrollView>
  )
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#f9fafb" },
  content: { padding: 20, paddingBottom: 40 },
  title: { fontSize: 22, fontWeight: "700", color: "#111827", marginBottom: 4 },
  subtitle: { fontSize: 13, color: "#6b7280", marginBottom: 20 },
  card: {
    backgroundColor: "#fff", borderRadius: 16, padding: 20, marginBottom: 16,
    shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2,
  },
  cardTitle: { fontSize: 15, fontWeight: "600", color: "#111827", marginBottom: 16 },
  periodRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  periodField: { flex: 1 },
  label: { fontSize: 11, fontWeight: "500", color: "#6b7280", marginBottom: 4 },
  periodValue: { fontSize: 14, fontWeight: "600", color: "#111827" },
  previewRow: { flexDirection: "row", justifyContent: "space-around", backgroundColor: "#f9fafb", borderRadius: 12, padding: 14, marginBottom: 16 },
  previewStat: { alignItems: "center" },
  previewStatValue: { fontSize: 22, fontWeight: "700", color: "#111827" },
  previewStatLabel: { fontSize: 11, color: "#6b7280", marginTop: 2 },
  btn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    backgroundColor: "#166534", borderRadius: 12, paddingVertical: 14,
  },
  btnDisabled: { opacity: 0.6 },
  btnText: { fontSize: 15, fontWeight: "600", color: "#fff" },
  hint: { fontSize: 11, color: "#9ca3af", textAlign: "center", marginTop: 12 },
  disclaimerCard: {
    flexDirection: "row", alignItems: "flex-start", gap: 10,
    backgroundColor: "#f0fdf4", borderRadius: 12, padding: 14,
    borderWidth: 1, borderColor: "#bbf7d0", marginBottom: 16,
  },
  disclaimerText: { flex: 1, fontSize: 12, color: "#166534", lineHeight: 17 },
  reportRow: { paddingVertical: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  reportRowBorder: { borderBottomWidth: 1, borderBottomColor: "#f3f4f6" },
  reportInfo: { flex: 1 },
  reportTitle: { fontSize: 13, fontWeight: "500", color: "#111827" },
  reportPeriod: { fontSize: 11, color: "#6b7280", marginTop: 2 },
  reportDate: { fontSize: 11, color: "#9ca3af", marginTop: 1 },
  reportRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  reportScore: { fontSize: 16, fontWeight: "700" },
  shareBtn: { padding: 4 },
  empty: { alignItems: "center", paddingVertical: 40 },
  emptyText: { fontSize: 15, fontWeight: "500", color: "#6b7280", marginTop: 12 },
  emptySubtext: { fontSize: 13, color: "#9ca3af", marginTop: 4 },
})
